#!/bin/bash
:

#set -x

SED=$(which sed)
AWK=$(which awk)
TAIL=$(which tail)
GREP=$(which grep)
MONGO=$(which mongo)
PREV_FILE=.mmm_prev
empty=0
#
#
USE_AUTH=false
PARAM_ERROR_STRING="Missing parameter name"
RETURN_CODE=0
##############


##############
usage(){

echo "Usage: $0 [-user|--user <username> -pwd|--pwd <password>]  -host|--host <hostname> -port|--port <port> -metrics|--metrics <metric1,metric2,metricN>"
echo "Supported metrics are: "
echo "globalLock.lockTime	- The value of lockTime represents the time, in microseconds, since the database last started, that the globalLock has been held. "
echo "globalLock.ratio		- The value of ratio displays the relationship between lockTime and totalTime."
echo "mem.resident		- The value of resident is roughly equivalent to the amount of RAM, in megabytes (MB), currently used by the database process. In normal use this value tends to grow. In dedicated database servers this number tends to approach the total amount of system memory.
"
echo "mem.virtual		- Virtual displays the quantity, in megabytes (MB), of virtual memory used by the mongod process."
echo "mem.mapped		- The value of mapped provides the amount of mapped memory, in megabytes (MB), by the database."
echo "connections.current	- The value of current corresponds to the number of connections to the database server from clients."
echo "connections.available	- available provides a count of the number of unused available connections that the database can provide. Consider this value in combination with the value of current to understand the connection load on the database, and the Linux ulimit Settings document for more information about system thresholds on available connections.
."
echo "backgroundFlushing.flushes - flushes is a counter that collects the number of times the database has flushed all writes to disk."
echo "backgroundFlushing.total_ms - The total_ms value provides the total number of milliseconds (ms) that the mongod processes have spent writing (i.e. flushing) data to disk"
echo "backgroundFlushing.average_ms - The average_ms value describes the relationship between the number of flushes and the total amount of time that the database has spent writing data to disk."
echo "backgroundFlushing.last_ms - The value of the last_ms field is the amount of time, in milliseconds, that the last flush operation took to complete"
echo "opcounters.insert  	- # of inserts per second (* means replicated op)"
echo "opcounters.query    	- query provides a counter of the total number of queries since the mongod instance last started.
"
echo "opcounters.update   	- update provides a counter of the total number of update operations since the mongod instance last started."
echo "opcounters.delete   	- delete provides a counter of the total number of delete operations since the mongod instance last started."
echo "opcounters.getmore  	- getmore provides a counter of the total number of “getmore” operations since the mongod instance last started. This counter can be high even if the query count is low. Secondary nodes send getMore operations as part of the replication process."
echo "opcounters.command  	- command provides a counter of the total number of commands issued to the database since the mongod instance last started."
echo "asserts.regular  	- The regular counter tracks the number of regular assertions raised since the server process started."
echo "asserts.warning   	- The warning counter tracks the number of warnings raised since the server process started."
echo "asserts.msg    	- The msg counter tracks the number of message assertions raised since the server process started."
echo "asserts.user      	- The user counter reports the number of “user asserts” that have occurred since the last time the server process started."
echo "asserts.rollovers   	- The rollovers counter displays the number of times that the rollover counters have rolled over since the last time the server process started."


        RETURN_CODE=1
        exit $RETURN_CODE
}
##################################################################################################
# Checking for required tools
##################################################################################################
if [[ -z $SED ]]
then
echo "sed not found"
exit 1
fi
#
if [[ -z $AWK ]]
then
echo "awk not found"
exit 1
fi
#
if [[ -z $MONGO ]]
then
echo "mongo not found"
exit 1
fi
#
if [[ -z $TAIL ]]
then
echo "tail not found"
exit 1
fi
#
if [[ -z $GREP ]]
then
echo "grep not found"
exit 1
fi
#
#
save(){
	echo "$1"|$SED -e 's/^[ \r]*//' > $PREV_FILE
}
#
###################################################################################################
# Checking for input parameters
###################################################################################################
if [[ $# -le 3 ]]
then
	usage
fi
while [ $# -gt 0 ]    # Until run out of parameters . . .
do
	case $1 in
    	-u | --user | -user )  			USERNAME="$2"; shift	;;
    	-p | --pwd | -pwd ) 			PSWD="$2"; shift	;;
    	-h | --host | -host )  			HOST="$2"; shift	;;
    	-t | --port | -port )  			PORT="$2"; shift	;;
    	-m | --metrics | -metrics )		METRICS="$2"; shift ;;
	-d | --database | -database )		DB="$2"; shift ;;
    	*) ;; # unknown option		
  	esac
  	shift
done
#
METRICS=${METRICS/'['/''}
METRICS=${METRICS/%']'/''}
#
if [[ -n $USERNAME ]]
then
	USE_AUTH=true
	if [ -z "$PSWD" ]; then
                echo "$PARAM_ERROR_STRING 'pwd'"
                RETURN_CODE=1
		exit $RETURN_CODE 
        fi

        if [ -z "$HOST" ]; then
                echo "$PARAM_ERROR_STRING 'host'"
                RETURN_CODE=1
		exit $RETURN_CODE
        fi

        if [ -z "$PORT" ]; then
                echo "$PARAM_ERROR_STRING 'port'"
                RETURN_CODE=1
		exit $RETURN_CODE
        fi
	if [ -z "$METRICS" ]; then
		echo "$PARAM_ERROR_STRING 'metrics'"
		RETURN_CODE=1
		exit $RETURN_CODE
	fi

fi
#

#
if [[ $USE_AUTH == true ]]
then
	MONGOSTAT_OPTS=" --host $HOST:$PORT -u $USER -p $PSWD"
else
	MONGOSTAT_OPTS=" --host $HOST:$PORT"
fi
#
if [[ ! -f $PREV_FILE || -z $(cat $PREV_FILE) ]]
then
	empty=1
	
fi
#
error=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()' $DB | $GREP -o 'exception')
if [[ $error == "exception" ]]
then
  echo "An error accured while connecting to mongodb"
  echo "Check host and port parameters"
  exit 1
fi
#
splited_metrics=$(echo $METRICS|tr ',' ' ')
NOW=$(date '+%s')
BEFORE=$(cat $PREV_FILE|grep 'timestamp'|$AWK '{print $2}')
if [[ -z $BEFORE ]];then
	BEFORE=0
fi
DIFFER=$(( $NOW - $BEFORE ))
if [[ 0 -eq $DIFFER ]]
then
	DIFFER=1
fi
save_value="timestamp "$(echo $NOW|$SED "s/$/\\`echo -e '\n\r'`/g")
#

mem_supported=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["mem"]["supported"]' $DB|$TAIL -1)
if [[ -z $mem_supported ]]
then
  mem_supported="false"
fi

#
for metric in $splited_metrics
do
	case "$metric" in

	"globalLock.lockTime")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'globalLock.lockTime'| $AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["globalLock"]["lockTime"]' $DB|$TAIL -1| $SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		current=$($AWK -vc=$current 'BEGIN{ print c / 1000000 }' | $SED -e 's/[eE]+*/\*10\^/')
		result=$($AWK -vc=$current -vp=$prev 'BEGIN{ print c - p }' | $SED -e 's/[eE]+*/\*10\^/')

	test -z $result && result=0

	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT globalLock.lockTime="$result
	save_value="$save_value globalLock.lockTime "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"globalLock.totalTime")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'globalLock.totalTime'| $AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["globalLock"]["totalTime"]' $DB|$TAIL -1| $SED -e 's/[eE]+*/\*10\^/' )
	if [[ -z $prev ]]
	then
		prev=0
	fi
		result=$($AWK -vc=$current -vp=$prev 'BEGIN{ print c - p }' | $SED -e 's/[eE]+*/\*10\^/')
	test -z $result && result=0

	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	result=$(printf %0.3f $result)
	totaltime=$result
	#
	save_value="$save_value globalLock.totalTime "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"globalLock.ratio")
#
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'globalLock.lockTime'| $AWK '{print $2}')
	_current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["globalLock"]["lockTime"]' $DB|$TAIL -1| $SED -e 's/[eE]+*/\*10\^/' )
	if [[ -z $prev ]]
	then
		prev=0
	fi
		current=$($AWK -vc=$_current 'BEGIN{ print c / 1000000 }' | $SED -e 's/[eE]+*/\*10\^/' )
		locktime=$($AWK -vc=$current -vp=$prev 'BEGIN{ print c - p }' | $SED -e 's/[eE]+*/\*10\^/' )
		
	test -z $current && current=1
	test -z $locktime && locktime=1
	locktime=$(printf %0.3f $locktime)
	
	if [[ 1 -eq $(echo "$locktime < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'globalLock.totalTime'| $AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["globalLock"]["totalTime"]' $DB|$TAIL -1| $SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		totaltime=$($AWK -vc=$current -vp=$prev 'BEGIN{ print c - p }' | $SED -e 's/[eE]+*/\*10\^/')
	
	if [[ 1 -eq $(echo "$totaltime < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
#	#
	#
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'globalLock.ratio'| $AWK '{print $2}')

	if [[ -z $prev ]]
	then
		prev=0 
	fi

	if [[ $(echo "$totaltime == 0"|bc) || -z $totaltime ]]
	then
		totaltime=1 # avoiding division by zero
	fi

	result=$($AWK -vc=$locktime -vp=$totaltime 'BEGIN{ print c / p }' )
	test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
		#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT globalLock.ratio="$result
	save_value="$save_value globalLock.ratio "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"mem.resident")
	if [[ $mem_supported == "true" ]]
	then
	  test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'mem.resident'|$AWK '{print $2}')
	  current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["mem"]["resident"]' $DB|$TAIL -1)
	  if [[ -z $prev ]]
	  then
		  prev=0
	  fi
	  result=$current
	  test -z $result && result=0
	  if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	  then
		  echo "wrongResult=true"
		  save "$save_value"
		  exit
	  fi
	  #
	#
	result=$(printf %0.3f $result)
	else
	  result=-1
	fi

	OUTPUT=" $OUTPUT mem.resident="$result
	save_value="$save_value mem.resident "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")

	;;
##########
	"mem.virtual")
	if [[ $mem_supported == "true" ]]
	then
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["mem"]["virtual"]' $DB|$TAIL -1)
	if [[ -z $prev ]]
	then
		prev=0
	fi
	result=$current
	test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	else
	  result=-1
	fi

	OUTPUT=" $OUTPUT mem.virtual="$result
	save_value="$save_value mem.virtual "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"mem.mapped")
	if [[ $mem_supported == "true" ]]
	then
	  current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["mem"]["mapped"]' $DB|$TAIL -1)
	  if [[ -z $prev ]]
	  then
		  prev=0
	  fi
	  result=$current
	  test -z $result && result=0
	  
	  if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	  then
		  echo "wrongResult=true"
		  save "$save_value"
		  exit
	  fi
	#
	#
	result=$(printf %0.3f $result)
	else
	  result=-1
	fi

	OUTPUT=" $OUTPUT mem.mapped="$result
	save_value="$save_value mem.mapped "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"connections.current")

	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["connections"]["current"]' $DB|$TAIL -1)
	if [[ -z $prev ]]
	then
		prev=0
	fi
	result=$current
	test -z $result && result=0	
	
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT connections.current="$result
	save_value="$save_value connections.current "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"connections.available")

	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["connections"]["available"]' $DB|$TAIL -1)
	if [[ -z $prev ]]
	then
		prev=0
	fi
	result=$current
	test -z $result && result=0	
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT connections.available="$result
	save_value="$save_value connections.available "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"backgroundFlushing.flushes")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'backgroundFlushing.flushes'| $AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["backgroundFlushing"]["flushes"]' $DB|$TAIL -1| $SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		result=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }' | $SED -e 's/[eE]+*/\*10\^/')

	
	test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT backgroundFlushing.flushes="$result
	save_value="$save_value backgroundFlushing.flushes "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"backgroundFlushing.total_ms")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'backgroundFlushing.total_ms'|$AWK '{print $2}')
	_current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["backgroundFlushing"]["total_ms"]' $DB|$TAIL -1| $SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		current=$($AWK -vc=$_current 'BEGIN { print c / 1000 }' | $SED -e 's/[eE]+*/\*10\^/')
		result=$($AWK -vc=$current -vp=$prev 'BEGIN { print c - p }' | $SED -e 's/[eE]+*/\*10\^/')
		totalms=$result
	test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT backgroundFlushing.total_ms="$result
	save_value="$save_value backgroundFlushing.total_ms "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"backgroundFlushing.average_ms")
#
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'backgroundFlushing.total_ms'|$AWK '{print $2}')
	_current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["backgroundFlushing"]["total_ms"]' $DB|$TAIL -1|$SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		current=$($AWK -vc=$_current 'BEGIN { print c / 1000 }'| $SED -e 's/[eE]+*/\*10\^/')
		totalms=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }'| $SED -e 's/[eE]+*/\*10\^/' )
		test -z $totalms && totalms=0
#
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'backgroundFlushing.flushes'|$AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["backgroundFlushing"]["flushes"]' $DB|$TAIL -1|$SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
	flushes=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }' | $SED -e 's/[eE]+*/\*10\^/')
	test -z $flushes && flushes=0
	
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	flushes=$(printf %0.3f $flushes)
	#
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'backgroundFlushing.average_ms'|$AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["backgroundFlushing"]["average_ms"]' $DB|$TAIL -1)
	if [[ -z $prev ]]
	then
		prev=0
	fi
		result=$($AWK -vc=$totalms -vp=$flushes 'BEGIN { print c / p }' | $SED -e 's/[eE]+*/\*10\^/')
		result=$(echo $result|$SED -e 's/[eE]+*/\*10\^/')
	
	test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT backgroundFlushing.average_ms="$result
	save_value="$save_value backgroundFlushing.average_ms "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"backgroundFlushing.last_ms")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'backgroundFlushing.last_ms'|$AWK '{print $2}')
	_current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["backgroundFlushing"]["last_ms"]' $DB|$TAIL -1|$SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		result=$($AWK -vc=$_current 'BEGIN { print c / 1000 }'| $SED -e 's/[eE]+*/\*10\^/')
		test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT backgroundFlushing.last_ms="$result
	save_value="$save_value backgroundFlushing.last_ms "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"opcounters.insert")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'opcounters.insert'|$AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["opcounters"]["insert"]' $DB|$TAIL -1| $SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		result=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }' |$SED -e 's/[eE]+*/\*10\^/')
		test -z $result && result=0
	
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT opcounters.insert="$result
	save_value="$save_value opcounters.insert "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
##########
	"opcounters.query")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'opcounters.query'|$AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["opcounters"]["query"]' $DB|$TAIL -1| $SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		result=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }'| $SED -e 's/[eE]+*/\*10\^/')
		test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT opcounters.query="$result
	save_value="$save_value opcounters.query "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"opcounters.update")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'opcounters.update'|$AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["opcounters"]["update"]' $DB|$TAIL -1| $SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		result=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }'| $SED -e 's/[eE]+*/\*10\^/')
		test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT opcounters.update="$result
	save_value="$save_value opcounters.update "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"opcounters.delete")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'opcounters.delete'|$AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["opcounters"]["delete"]' $DB|$TAIL -1| $SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		result=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }'| $SED -e 's/[eE]+*/\*10\^/')
	test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi

	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT opcounters.delete="$result
	save_value="$save_value opcounters.delete "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"opcounters.getmore")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'opcounters.getmore'|$AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["opcounters"]["getmore"]' $DB|$TAIL -1| $SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
	result=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }'| $SED -e 's/[eE]+*/\*10\^/')
	test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT opcounters.getmore="$result
	save_value="$save_value opcounters.getmore "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"opcounters.command")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'opcounters.command'|$AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["opcounters"]["command"]' $DB|$TAIL -1| $SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
	result=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }'|$SED -e 's/[eE]+*/\*10\^/')
	test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT opcounters.command="$result
	save_value="$save_value opcounters.command "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"asserts.regular")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'asserts.regular'|$AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["asserts"]["regular"]' $DB|$TAIL -1|$SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		result=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }'|$SED -e 's/[eE]+*/\*10\^/')
		test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT asserts.regular="$result
	save_value="$save_value asserts.regular "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"asserts.warning")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'asserts.warning'|$AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["asserts"]["warning"]' $DB|$TAIL -1|$SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		result=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }'|$SED -e 's/[eE]+*/\*10\^/')
		test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT asserts.warning="$result
	save_value="$save_value asserts.warning "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"asserts.msg")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'asserts.msg'|$AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["asserts"]["msg"]' $DB|$TAIL -1|$SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		result=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }'| $SED -e 's/[eE]+*/\*10\^/')
		test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT asserts.msg="$result
	save_value="$save_value asserts.msg "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"asserts.user")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'asserts.user'|$AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["asserts"]["user"]' $DB|$TAIL -1|$SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
		result=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }'| $SED -e 's/[eE]+*/\*10\^/')
		test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT asserts.user="$result
	save_value="$save_value asserts.user "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
	"asserts.rollovers")
	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'asserts.rollovers'|$AWK '{print $2}')
	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["asserts"]["rollovers"]' $DB|$TAIL -1|$SED -e 's/[eE]+*/\*10\^/')
	if [[ -z $prev ]]
	then
		prev=0
	fi
	result=$($AWK -vc=$current -vp=$prev -vd=$DIFFER 'BEGIN { print (c - p) / d }' | $SED -e 's/[eE]+*/\*10\^/')
	test -z $result && result=0
	if [[ 1 -eq $(echo "$result < 0"|bc) ]]
	then
		echo "wrongResult=true"
		save "$save_value"
		exit
	fi
	#
	#
	result=$(printf %0.3f $result)
	OUTPUT=" $OUTPUT asserts.rollovers="$result
	save_value="$save_value asserts.rollovers "$(echo $current|$SED "s/$/\\`echo -e '\n\r'`/g")
	;;
##########
esac
done
#
save "$save_value"
#
if [[ $empty -eq 1 ]]
then
	echo "wrongResult=true"
	save "$save_value"
else
	echo $OUTPUT
fi

exit $RETURN_CODE

