#!/bin/bash
#############################################################################
#	COUCH-DB MONITOR START SCRIPT                                           #
#	Author: Arthur Tumanyan <arthurtumanyan@yahoo.com>                  #
#	Company: Netangels <http://www.netangels.net>                       # 
#############################################################################
#
#set -x
# sources included
SOURCE_PATH=
source ${SOURCE_PATH}monitis_constant.sh || exit 2
source ${SOURCE_PATH}monitis_util.sh || exit 2
source ${SOURCE_PATH}monitis_api.sh || exit 2
source ${SOURCE_PATH}monitis_data.sh || exit 2

echo "***CouchDB Monitor start with following parameters***"
echo "Monitor name = $MONITOR_NAME"
echo "Monitor tag = $MONITOR_TAG"
echo "Monitor type = $MONITOR_TYPE"

# obtaining TOKEN
get_token
ret="$?"
if [[ ($ret -ne 0) ]]
then
	error 3 "$MSG"
else
	echo RECEIVE TOKEN: "$TOKEN" at `date -u -d @$(( $TOKEN_OBTAIN_TIME/1000 ))`
	echo "All is OK for now."
fi
#
get_data
RESULT_PARAMS="$result"
RESULT_POSTDATA=$postdata
ADD_RESULT_PARAMS="$additionalResult"
ADD_RESULT_POSTDATA="$additionalPData"
#
#
echo
#
MONITOR_ID=`get_monitorID $MONITOR_NAME $MONITOR_TAG $MONITOR_TYPE `
ret="$?"
if [[ ($ret -ne 0) ]]
then
	echo "Monitor isn't found - create a new one..."
	echo "RESULT_PARAMS = $RESULT_PARAMS"
	# Adding custom monitor
	add_custom_monitor "$MONITOR_NAME" "$MONITOR_TAG" "$RESULT_PARAMS" "$ADD_RESULT_PARAMS" "$MONITOR_TYPE"
	ret="$?"
	if [[ ($ret -ne 0) ]]
	then
		error "$ret" "$MSG"
	fi
fi

if [[ ($MONITOR_ID -le 0) ]]
then 
	echo MonitorId is still zero
		error "Could not get monitor id from local cache [.monitor.id]"
	else
		echo Custom monitor id = "$MONITOR_ID"
		echo "All is OK for now."
fi



	# Compose monitor data

	echo "Add custom data..."	
	echo "PostDat = $RESULT_POSTDATA"

	timestamp=`get_timestamp`
	# Sending to Monitis
	add_custom_monitor_data $RESULT_POSTDATA $timestamp
	ret="$?"
	if [[ ($ret -ne 0) ]];then
		error "$ret" "$MSG"
		exit 8
	else
		echo $( date +"%D %T" ) - The Custom monitor data were successfully added
	fi
	
                                add_custom_monitor_additional_data "$ADD_RESULT_POSTDATA" $timestamp
                                ret="$?"
                                if [[ ($ret -ne 0) ]]
                                then
                                        error "$ret" "$MSG"
                                else
                                        echo $( date +"%D %T" ) - The Custom monitor additional data were successfully added
                                fi



